---- COMMUNITY USERS, TABLESPACE AND DATABASE CREATION SCRIPT
---- Execution by super user
CREATE ROLE CUSTOMER WITH CREATEDB LOGIN PASSWORD 'passcommunity';

---- TABLESPACE CREATION
CREATE TABLESPACE CUSTOMER OWNER CUSTOMER LOCATION '/opt/app-root';

---- DATABASE CREATION
CREATE DATABASE CUSTOMER WITH OWNER CUSTOMER TABLESPACE = CUSTOMER;
ALTER ROLE CUSTOMER SET DEFAULT_TABLESPACE TO CUSTOMER;
REVOKE CONNECT ON DATABASE CUSTOMER FROM public;

-- GRANT ROLES TO COMMUNITY_APP_RW
CREATE ROLE CUSTOMER_APP_RW WITH LOGIN PASSWORD 'passcommunity';
ALTER ROLE CUSTOMER_APP_RW SET DEFAULT_TABLESPACE TO CUSTOMER;