---- EXECUTED BY COMMUNITY USER
---- CREATE SCHEMA
CREATE SCHEMA IF NOT EXISTS CUSTOMER AUTHORIZATION CUSTOMER;
---- Default schema on database
ALTER DATABASE CUSTOMER SET SEARCH_PATH TO CUSTOMER;
GRANT USAGE ON SCHEMA CUSTOMER TO CUSTOMER_APP_RW;

-- GRANT ALL PRIVILEGES IN SCHEMA COMMUNITY ON TABLES TO COMMUNITY_APP_RW;
-- GRANT ALL PRIVILEGES IN SCHEMA COMMUNITY ON SEQUENCES TO COMMUNITY_APP_RW;

-- ANY TABLES AND SEQUENCES will be accessible from COMMUNITY_APP_RW
ALTER DEFAULT PRIVILEGES IN SCHEMA CUSTOMER GRANT ALL PRIVILEGES ON TABLES TO CUSTOMER_APP_RW;
ALTER DEFAULT PRIVILEGES IN SCHEMA CUSTOMER GRANT ALL PRIVILEGES ON SEQUENCES TO CUSTOMER_APP_RW;

-- Read only access to public schema within COMMUNITY Database
GRANT USAGE ON SCHEMA public to CUSTOMER_APP_RW;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO CUSTOMER_APP_RW;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO CUSTOMER_APP_RW;

GRANT CONNECT, TEMPORARY, TEMP ON DATABASE CUSTOMER TO CUSTOMER_APP_RW;