---- Execution by USER/ROLE COMMUNITY
BEGIN;


---- Budget Template

CREATE TABLE CUSTOMERS (
  id                  NUMERIC(19, 0) NOT NULL,
  first_name          VARCHAR(255) NOT NULL,
  last_name           VARCHAR(255) NOT NULL
) TABLESPACE CUSTOMER;

ALTER TABLE CUSTOMERS ADD CONSTRAINT customers_PK PRIMARY KEY (id) USING INDEX TABLESPACE CUSTOMER;

COMMENT ON TABLE CUSTOMERS IS 'Holds the members community';

GRANT ALL ON CUSTOMERS TO CUSTOMER_APP_RW;


COMMIT;